services:
  postgres:
    image: postgres:17
    container_name: mymusic-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: mymusic
      POSTGRES_USER: mymusic
      POSTGRES_PASSWORD: mymusic_dev_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
